// Generated by CoffeeScript 1.6.3
(function() {
  var T, def;

  T = require("./t");

  def = require("./def");

  module.exports = {
    T: require("./t"),
    def: require("./def"),
    defun: function(args, returns, f) {
      return def(T.Func(args, returns), f);
    },
    option: require("./option")
  };

}).call(this);
